[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "anti-paste-guard"
version = "0.0.1"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
where = ["."]
include = ["app", "core", "ui"]
